import NetworkPersonOne from "../../assets/Images/network/networkPersonOne.png";
import NetworkPersonTwo from "../../assets/Images/network/networkPersonTwo.png";
import NetworkLogo from "../../assets/Icons/network/net_logo.svg";
import NetworkPersonThree from "../../assets/Images/network/networkPersonThree.png";
import NetworkPersonFour from "../../assets/Images/network/networkPersonFour.png";
import NetworkPersonFive from "../../assets/Images/network/networkPersonFive.png";
import NetworkPersonSix from "../../assets/Images/network/networkPersonSix.png";
import NetworkPersonSeven from "../../assets/Images/network/networkPersonEight.png";
import NetworkPersonEight from "../../assets/Images/network/networkPersonNine.png";
import NetworkPersonNine from "../../assets/Images/network/networkPersonSeven.png";

export const images = [
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
];

export const edges = [
  { from: 1, to: 2 },
  { from: 1, to: 3 },
  { from: 3, to: 4 },
  { from: 1, to: 4 },
  { from: 1, to: 5 },
  { from: 1, to: 6 },
  { from: 6, to: 7 },
  { from: 2, to: 8 },
];

export const options = {
  edges: {
    color: "#49494A",
  },
  // layout: {
  //   randomSeed: undefined,
  // },
  physics: false,
  interaction: {
    dragNodes: false,
    dragView: false,
    zoomView: false,
  },
  height: "100%",
  width: "100%",
  nodes: {
    borderWidth: 4,
    size: 41,
    color: {
      border: "#222222",
    },
  },
};
