import NetworkPersonOne from "../../assets/Images/network/networkPersonOne.png";
import NetworkPersonTwo from "../../assets/Images/network/networkPersonTwo.png";
import NetworkPersonThree from "../../assets/Images/network/networkPersonThree.png";
import NetworkPersonFour from "../../assets/Images/network/networkPersonFour.png";
import NetworkPersonFive from "../../assets/Images/network/networkPersonFive.png";
import NetworkPersonSix from "../../assets/Images/network/networkPersonSix.png";
import NetworkPersonSeven from "../../assets/Images/network/networkPersonEight.png";
import NetworkPersonEight from "../../assets/Images/network/networkPersonNine.png";
import NetworkPersonNine from "../../assets/Images/network/networkPersonSeven.png";

export const images = [
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
];

export const edges = [
  { from: 1, to: 2 },
  { from: 2, to: 4 },
  { from: 1, to: 3 },
  { from: 3, to: 2 },
  { from: 3, to: 5 },
  { from: 6, to: 2 },
  { from: 1, to: 6 },
  { from: 1, to: 8 },
  { from: 5, to: 8 },
  { from: 6, to: 7 },
  { from: 8, to: 9 },
  { from: 2, to: 10 },
];

export const options = {
  edges: {
    color: "#49494ACF",
    width: 3.3,
  },
  physics: false,
  interaction: {
    dragNodes: false,
    dragView: false,
    zoomView: false,
  },
  height: "100%",
  width: "100%",
};

export const imagePostion = [
  {
    id: 1,
    x: -300,
    y: -60,
  },
  {
    id: 2,
    x: -330,
    y: 240,
  },
  {
    id: 3,
    x: -100,
    y: 150,
  },
  {
    id: 4,
    x: -200,
    y: 410,
  },
  {
    id: 5,
    x: -590,
    y: -200,
  },
  {
    id: 6,
    x: -870,
    y: -150,
  },
  {
    id: 7,
    x: -800,
    y: 150,
  },
  {
    id: 8,
    x: -870,
    y: 400,
  },
  {
    id: 1,
    x: -60,
    y: -190,
  },
];
