import NetworkPersonOne from "../../assets/Images/network/networkPersonOne.png";
import NetworkPersonTwo from "../../assets/Images/network/networkPersonTwo.png";
import NetworkPersonThree from "../../assets/Images/network/networkPersonThree.png";
import NetworkPersonFour from "../../assets/Images/network/networkPersonFour.png";
import NetworkPersonFive from "../../assets/Images/network/networkPersonFive.png";
import NetworkPersonSix from "../../assets/Images/network/networkPersonSix.png";
import NetworkPersonSeven from "../../assets/Images/network/networkPersonEight.png";
import NetworkPersonEight from "../../assets/Images/network/networkPersonNine.png";
import NetworkPersonNine from "../../assets/Images/network/networkPersonSeven.png";

export const images = [
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonTwo },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonThree },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFour },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonFive },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSix },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonSeven },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonEight },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonNine },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
  { image: NetworkPersonOne },
];

export const edges = [
  { from: 1, to: 2 },
  { from: 2, to: 3 },
  { from: 1, to: 6 },
  { from: 1, to: 9 },
  { from: 2, to: 5 },
  { from: 2, to: 7 },
  { from: 2, to: 6 },
  { from: 1, to: 3 },
  { from: 3, to: 4 },
  { from: 6, to: 8 },
  { from: 8, to: 9 },
  { from: 9, to: 10 },
];

export const options = {
  edges: {
    color: "#49494ACF",
    width: 3.3,
  },
  physics: false,
  interaction: {
    dragNodes: false,
    dragView: false,
    zoomView: false,
  },
  height: "100%",
  width: "100%",
};

export const imagePostion = [
  {
    id: 1,
    x: 20,
    y: -190,
  },
  {
    id: 2,
    x: -410,
    y: -550,
  },
  {
    id: 3,
    x: -700,
    y: -300,
  },
  {
    id: 4,
    x: 330,
    y: -250,
  },
  {
    id: 5,
    x: 10,
    y: 100,
  },
  {
    id: 6,
    x: 250,
    y: 60,
  },
  {
    id: 7,
    x: 150,
    y: 330,
  },
  {
    id: 8,
    x: -670,
    y: 40,
  },
  {
    id: 9,
    x: -770,
    y: 550,
  },
];

export const showImages = 9;
